// Code generated from Minecraft 26.2 client.jar data/ by scripts/gen_registries.py. DO NOT EDIT.
package server

import "github.com/zakla/mc-server/pkg/protocol"

// vanillaSyncRegistries lists every synchronized registry with its real
// vanilla entry names. Per-entry NBT is omitted; the client fills it from
// its known pack (minecraft:core 26.2) agreed during configuration.
var vanillaSyncRegistries = []Registry{
	{ID: "minecraft:banner_pattern", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:base"},
		{Name: "minecraft:border"},
		{Name: "minecraft:bricks"},
		{Name: "minecraft:circle"},
		{Name: "minecraft:creeper"},
		{Name: "minecraft:cross"},
		{Name: "minecraft:curly_border"},
		{Name: "minecraft:diagonal_left"},
		{Name: "minecraft:diagonal_right"},
		{Name: "minecraft:diagonal_up_left"},
		{Name: "minecraft:diagonal_up_right"},
		{Name: "minecraft:flow"},
		{Name: "minecraft:flower"},
		{Name: "minecraft:globe"},
		{Name: "minecraft:gradient"},
		{Name: "minecraft:gradient_up"},
		{Name: "minecraft:guster"},
		{Name: "minecraft:half_horizontal"},
		{Name: "minecraft:half_horizontal_bottom"},
		{Name: "minecraft:half_vertical"},
		{Name: "minecraft:half_vertical_right"},
		{Name: "minecraft:mojang"},
		{Name: "minecraft:piglin"},
		{Name: "minecraft:rhombus"},
		{Name: "minecraft:skull"},
		{Name: "minecraft:small_stripes"},
		{Name: "minecraft:square_bottom_left"},
		{Name: "minecraft:square_bottom_right"},
		{Name: "minecraft:square_top_left"},
		{Name: "minecraft:square_top_right"},
		{Name: "minecraft:straight_cross"},
		{Name: "minecraft:stripe_bottom"},
		{Name: "minecraft:stripe_center"},
		{Name: "minecraft:stripe_downleft"},
		{Name: "minecraft:stripe_downright"},
		{Name: "minecraft:stripe_left"},
		{Name: "minecraft:stripe_middle"},
		{Name: "minecraft:stripe_right"},
		{Name: "minecraft:stripe_top"},
		{Name: "minecraft:triangle_bottom"},
		{Name: "minecraft:triangle_top"},
		{Name: "minecraft:triangles_bottom"},
		{Name: "minecraft:triangles_top"},
	}},
	{ID: "minecraft:worldgen/biome", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:badlands"},
		{Name: "minecraft:bamboo_jungle"},
		{Name: "minecraft:basalt_deltas"},
		{Name: "minecraft:beach"},
		{Name: "minecraft:birch_forest"},
		{Name: "minecraft:cherry_grove"},
		{Name: "minecraft:cold_ocean"},
		{Name: "minecraft:crimson_forest"},
		{Name: "minecraft:dark_forest"},
		{Name: "minecraft:deep_cold_ocean"},
		{Name: "minecraft:deep_dark"},
		{Name: "minecraft:deep_frozen_ocean"},
		{Name: "minecraft:deep_lukewarm_ocean"},
		{Name: "minecraft:deep_ocean"},
		{Name: "minecraft:desert"},
		{Name: "minecraft:dripstone_caves"},
		{Name: "minecraft:end_barrens"},
		{Name: "minecraft:end_highlands"},
		{Name: "minecraft:end_midlands"},
		{Name: "minecraft:eroded_badlands"},
		{Name: "minecraft:flower_forest"},
		{Name: "minecraft:forest"},
		{Name: "minecraft:frozen_ocean"},
		{Name: "minecraft:frozen_peaks"},
		{Name: "minecraft:frozen_river"},
		{Name: "minecraft:grove"},
		{Name: "minecraft:ice_spikes"},
		{Name: "minecraft:jagged_peaks"},
		{Name: "minecraft:jungle"},
		{Name: "minecraft:lukewarm_ocean"},
		{Name: "minecraft:lush_caves"},
		{Name: "minecraft:mangrove_swamp"},
		{Name: "minecraft:meadow"},
		{Name: "minecraft:mushroom_fields"},
		{Name: "minecraft:nether_wastes"},
		{Name: "minecraft:ocean"},
		{Name: "minecraft:old_growth_birch_forest"},
		{Name: "minecraft:old_growth_pine_taiga"},
		{Name: "minecraft:old_growth_spruce_taiga"},
		{Name: "minecraft:pale_garden"},
		{Name: "minecraft:plains"},
		{Name: "minecraft:river"},
		{Name: "minecraft:savanna"},
		{Name: "minecraft:savanna_plateau"},
		{Name: "minecraft:small_end_islands"},
		{Name: "minecraft:snowy_beach"},
		{Name: "minecraft:snowy_plains"},
		{Name: "minecraft:snowy_slopes"},
		{Name: "minecraft:snowy_taiga"},
		{Name: "minecraft:soul_sand_valley"},
		{Name: "minecraft:sparse_jungle"},
		{Name: "minecraft:stony_peaks"},
		{Name: "minecraft:stony_shore"},
		{Name: "minecraft:sulfur_caves"},
		{Name: "minecraft:sunflower_plains"},
		{Name: "minecraft:swamp"},
		{Name: "minecraft:taiga"},
		{Name: "minecraft:the_end"},
		{Name: "minecraft:the_void"},
		{Name: "minecraft:warm_ocean"},
		{Name: "minecraft:warped_forest"},
		{Name: "minecraft:windswept_forest"},
		{Name: "minecraft:windswept_gravelly_hills"},
		{Name: "minecraft:windswept_hills"},
		{Name: "minecraft:windswept_savanna"},
		{Name: "minecraft:wooded_badlands"},
	}},
	{ID: "minecraft:cat_sound_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:classic"},
		{Name: "minecraft:royal"},
	}},
	{ID: "minecraft:cat_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:all_black"},
		{Name: "minecraft:black"},
		{Name: "minecraft:british_shorthair"},
		{Name: "minecraft:calico"},
		{Name: "minecraft:jellie"},
		{Name: "minecraft:persian"},
		{Name: "minecraft:ragdoll"},
		{Name: "minecraft:red"},
		{Name: "minecraft:siamese"},
		{Name: "minecraft:tabby"},
		{Name: "minecraft:white"},
	}},
	{ID: "minecraft:chat_type", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:chat"},
		{Name: "minecraft:emote_command"},
		{Name: "minecraft:msg_command_incoming"},
		{Name: "minecraft:msg_command_outgoing"},
		{Name: "minecraft:say_command"},
		{Name: "minecraft:team_msg_command_incoming"},
		{Name: "minecraft:team_msg_command_outgoing"},
	}},
	{ID: "minecraft:chicken_sound_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:classic"},
		{Name: "minecraft:picky"},
	}},
	{ID: "minecraft:chicken_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:cold"},
		{Name: "minecraft:temperate"},
		{Name: "minecraft:warm"},
	}},
	{ID: "minecraft:cow_sound_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:classic"},
		{Name: "minecraft:moody"},
	}},
	{ID: "minecraft:cow_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:cold"},
		{Name: "minecraft:temperate"},
		{Name: "minecraft:warm"},
	}},
	{ID: "minecraft:damage_type", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:arrow"},
		{Name: "minecraft:bad_respawn_point"},
		{Name: "minecraft:cactus"},
		{Name: "minecraft:campfire"},
		{Name: "minecraft:cramming"},
		{Name: "minecraft:dragon_breath"},
		{Name: "minecraft:drown"},
		{Name: "minecraft:dry_out"},
		{Name: "minecraft:ender_pearl"},
		{Name: "minecraft:explosion"},
		{Name: "minecraft:fall"},
		{Name: "minecraft:falling_anvil"},
		{Name: "minecraft:falling_block"},
		{Name: "minecraft:falling_stalactite"},
		{Name: "minecraft:fireball"},
		{Name: "minecraft:fireworks"},
		{Name: "minecraft:fly_into_wall"},
		{Name: "minecraft:freeze"},
		{Name: "minecraft:generic"},
		{Name: "minecraft:generic_kill"},
		{Name: "minecraft:hot_floor"},
		{Name: "minecraft:in_fire"},
		{Name: "minecraft:in_wall"},
		{Name: "minecraft:indirect_magic"},
		{Name: "minecraft:lava"},
		{Name: "minecraft:lightning_bolt"},
		{Name: "minecraft:mace_smash"},
		{Name: "minecraft:magic"},
		{Name: "minecraft:mob_attack"},
		{Name: "minecraft:mob_attack_no_aggro"},
		{Name: "minecraft:mob_projectile"},
		{Name: "minecraft:on_fire"},
		{Name: "minecraft:out_of_world"},
		{Name: "minecraft:outside_border"},
		{Name: "minecraft:player_attack"},
		{Name: "minecraft:player_explosion"},
		{Name: "minecraft:sonic_boom"},
		{Name: "minecraft:spear"},
		{Name: "minecraft:spit"},
		{Name: "minecraft:stalagmite"},
		{Name: "minecraft:starve"},
		{Name: "minecraft:sting"},
		{Name: "minecraft:sulfur_cube_hot"},
		{Name: "minecraft:sweet_berry_bush"},
		{Name: "minecraft:thorns"},
		{Name: "minecraft:thrown"},
		{Name: "minecraft:trident"},
		{Name: "minecraft:unattributed_fireball"},
		{Name: "minecraft:wind_charge"},
		{Name: "minecraft:wither"},
		{Name: "minecraft:wither_skull"},
	}},
	{ID: "minecraft:dialog", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:custom_options"},
		{Name: "minecraft:quick_actions"},
		{Name: "minecraft:server_links"},
	}},
	{ID: "minecraft:dimension_type", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:overworld"},
		{Name: "minecraft:overworld_caves"},
		{Name: "minecraft:the_end"},
		{Name: "minecraft:the_nether"},
	}},
	{ID: "minecraft:enchantment", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:aqua_affinity"},
		{Name: "minecraft:bane_of_arthropods"},
		{Name: "minecraft:binding_curse"},
		{Name: "minecraft:blast_protection"},
		{Name: "minecraft:breach"},
		{Name: "minecraft:channeling"},
		{Name: "minecraft:density"},
		{Name: "minecraft:depth_strider"},
		{Name: "minecraft:efficiency"},
		{Name: "minecraft:feather_falling"},
		{Name: "minecraft:fire_aspect"},
		{Name: "minecraft:fire_protection"},
		{Name: "minecraft:flame"},
		{Name: "minecraft:fortune"},
		{Name: "minecraft:frost_walker"},
		{Name: "minecraft:impaling"},
		{Name: "minecraft:infinity"},
		{Name: "minecraft:knockback"},
		{Name: "minecraft:looting"},
		{Name: "minecraft:loyalty"},
		{Name: "minecraft:luck_of_the_sea"},
		{Name: "minecraft:lunge"},
		{Name: "minecraft:lure"},
		{Name: "minecraft:mending"},
		{Name: "minecraft:multishot"},
		{Name: "minecraft:piercing"},
		{Name: "minecraft:power"},
		{Name: "minecraft:projectile_protection"},
		{Name: "minecraft:protection"},
		{Name: "minecraft:punch"},
		{Name: "minecraft:quick_charge"},
		{Name: "minecraft:respiration"},
		{Name: "minecraft:riptide"},
		{Name: "minecraft:sharpness"},
		{Name: "minecraft:silk_touch"},
		{Name: "minecraft:smite"},
		{Name: "minecraft:soul_speed"},
		{Name: "minecraft:sweeping_edge"},
		{Name: "minecraft:swift_sneak"},
		{Name: "minecraft:thorns"},
		{Name: "minecraft:unbreaking"},
		{Name: "minecraft:vanishing_curse"},
		{Name: "minecraft:wind_burst"},
	}},
	{ID: "minecraft:enchantment_provider", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:enderman_loot_drop"},
		{Name: "minecraft:mob_spawn_equipment"},
		{Name: "minecraft:pillager_spawn_crossbow"},
	}},
	{ID: "minecraft:frog_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:cold"},
		{Name: "minecraft:temperate"},
		{Name: "minecraft:warm"},
	}},
	{ID: "minecraft:instrument", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:admire_goat_horn"},
		{Name: "minecraft:call_goat_horn"},
		{Name: "minecraft:dream_goat_horn"},
		{Name: "minecraft:feel_goat_horn"},
		{Name: "minecraft:ponder_goat_horn"},
		{Name: "minecraft:seek_goat_horn"},
		{Name: "minecraft:sing_goat_horn"},
		{Name: "minecraft:yearn_goat_horn"},
	}},
	{ID: "minecraft:jukebox_song", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:11"},
		{Name: "minecraft:13"},
		{Name: "minecraft:5"},
		{Name: "minecraft:blocks"},
		{Name: "minecraft:bounce"},
		{Name: "minecraft:cat"},
		{Name: "minecraft:chirp"},
		{Name: "minecraft:creator"},
		{Name: "minecraft:creator_music_box"},
		{Name: "minecraft:far"},
		{Name: "minecraft:lava_chicken"},
		{Name: "minecraft:mall"},
		{Name: "minecraft:mellohi"},
		{Name: "minecraft:otherside"},
		{Name: "minecraft:pigstep"},
		{Name: "minecraft:precipice"},
		{Name: "minecraft:relic"},
		{Name: "minecraft:stal"},
		{Name: "minecraft:strad"},
		{Name: "minecraft:tears"},
		{Name: "minecraft:wait"},
		{Name: "minecraft:ward"},
	}},
	{ID: "minecraft:painting_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:alban"},
		{Name: "minecraft:aztec"},
		{Name: "minecraft:aztec2"},
		{Name: "minecraft:backyard"},
		{Name: "minecraft:baroque"},
		{Name: "minecraft:bomb"},
		{Name: "minecraft:bouquet"},
		{Name: "minecraft:burning_skull"},
		{Name: "minecraft:bust"},
		{Name: "minecraft:cavebird"},
		{Name: "minecraft:changing"},
		{Name: "minecraft:cotan"},
		{Name: "minecraft:courbet"},
		{Name: "minecraft:creebet"},
		{Name: "minecraft:dennis"},
		{Name: "minecraft:donkey_kong"},
		{Name: "minecraft:earth"},
		{Name: "minecraft:endboss"},
		{Name: "minecraft:fern"},
		{Name: "minecraft:fighters"},
		{Name: "minecraft:finding"},
		{Name: "minecraft:fire"},
		{Name: "minecraft:graham"},
		{Name: "minecraft:humble"},
		{Name: "minecraft:kebab"},
		{Name: "minecraft:lowmist"},
		{Name: "minecraft:match"},
		{Name: "minecraft:meditative"},
		{Name: "minecraft:orb"},
		{Name: "minecraft:owlemons"},
		{Name: "minecraft:passage"},
		{Name: "minecraft:pigscene"},
		{Name: "minecraft:plant"},
		{Name: "minecraft:pointer"},
		{Name: "minecraft:pond"},
		{Name: "minecraft:pool"},
		{Name: "minecraft:prairie_ride"},
		{Name: "minecraft:sea"},
		{Name: "minecraft:skeleton"},
		{Name: "minecraft:skull_and_roses"},
		{Name: "minecraft:stage"},
		{Name: "minecraft:sunflowers"},
		{Name: "minecraft:sunset"},
		{Name: "minecraft:tides"},
		{Name: "minecraft:unpacked"},
		{Name: "minecraft:void"},
		{Name: "minecraft:wanderer"},
		{Name: "minecraft:wasteland"},
		{Name: "minecraft:water"},
		{Name: "minecraft:wind"},
		{Name: "minecraft:wither"},
	}},
	{ID: "minecraft:pig_sound_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:big"},
		{Name: "minecraft:classic"},
		{Name: "minecraft:mini"},
	}},
	{ID: "minecraft:pig_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:cold"},
		{Name: "minecraft:temperate"},
		{Name: "minecraft:warm"},
	}},
	{ID: "minecraft:sulfur_cube_archetype", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:bouncy"},
		{Name: "minecraft:explosive"},
		{Name: "minecraft:fast_flat"},
		{Name: "minecraft:fast_sliding"},
		{Name: "minecraft:high_resistance"},
		{Name: "minecraft:hot"},
		{Name: "minecraft:light"},
		{Name: "minecraft:regular"},
		{Name: "minecraft:slow_bouncy"},
		{Name: "minecraft:slow_flat"},
		{Name: "minecraft:slow_sliding"},
		{Name: "minecraft:sticky"},
	}},
	{ID: "minecraft:test_environment", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:default"},
	}},
	{ID: "minecraft:test_instance", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:always_pass"},
	}},
	{ID: "minecraft:timeline", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:day"},
		{Name: "minecraft:early_game"},
		{Name: "minecraft:moon"},
		{Name: "minecraft:villager_schedule"},
	}},
	{ID: "minecraft:trim_material", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:amethyst"},
		{Name: "minecraft:copper"},
		{Name: "minecraft:diamond"},
		{Name: "minecraft:emerald"},
		{Name: "minecraft:gold"},
		{Name: "minecraft:iron"},
		{Name: "minecraft:lapis"},
		{Name: "minecraft:netherite"},
		{Name: "minecraft:quartz"},
		{Name: "minecraft:redstone"},
		{Name: "minecraft:resin"},
	}},
	{ID: "minecraft:trim_pattern", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:bolt"},
		{Name: "minecraft:coast"},
		{Name: "minecraft:dune"},
		{Name: "minecraft:eye"},
		{Name: "minecraft:flow"},
		{Name: "minecraft:host"},
		{Name: "minecraft:raiser"},
		{Name: "minecraft:rib"},
		{Name: "minecraft:sentry"},
		{Name: "minecraft:shaper"},
		{Name: "minecraft:silence"},
		{Name: "minecraft:snout"},
		{Name: "minecraft:spire"},
		{Name: "minecraft:tide"},
		{Name: "minecraft:vex"},
		{Name: "minecraft:ward"},
		{Name: "minecraft:wayfinder"},
		{Name: "minecraft:wild"},
	}},
	{ID: "minecraft:wolf_sound_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:angry"},
		{Name: "minecraft:big"},
		{Name: "minecraft:classic"},
		{Name: "minecraft:cute"},
		{Name: "minecraft:grumpy"},
		{Name: "minecraft:puglin"},
		{Name: "minecraft:sad"},
	}},
	{ID: "minecraft:wolf_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:ashen"},
		{Name: "minecraft:black"},
		{Name: "minecraft:chestnut"},
		{Name: "minecraft:pale"},
		{Name: "minecraft:rusty"},
		{Name: "minecraft:snowy"},
		{Name: "minecraft:spotted"},
		{Name: "minecraft:striped"},
		{Name: "minecraft:woods"},
	}},
	{ID: "minecraft:world_clock", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:overworld"},
		{Name: "minecraft:the_end"},
	}},
	{ID: "minecraft:zombie_nautilus_variant", Entries: []protocol.RegistryEntry{
		{Name: "minecraft:temperate"},
		{Name: "minecraft:warm"},
	}},
}
